apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-app
  namespace: todo-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      containers:
      - name: todo-app

        image: dockerforlearning0213/todo-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        env:
        - name: DB_HOST
          value: mysql

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
