apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: todo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      automountServiceAccountToken: false

      containers:
      - name: mysql

        image: mysql:8.0

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3306

        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "500Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"

        envFrom:
        - secretRef:
            name: mysql-secret

        - configMapRef:
            name: mysql-config

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
